### ISSUE TITLE
Moving code to the Ceph organization?

### ISSUE THREAD

**Issue by leseb** [IrekFasikhov/go-rgwadmin#5]
Hi @IrekFasikhov, 

Great work on that library!
I'm not sure if you are aware but the Ceph organization has a repository that centralizes go-binding from various Ceph components (currently RBD and CephFS). With the go-ceph team, we believe that go-ceph could benefit from this library and the other way around.
Having an official "home" under the Ceph organization banner is always good to get more traction, maintenance, and improvement.

It seems that there is no licensing issue (we can import GPL code in MIT), so let us know if you are on board with the idea and I can take care of moving the code and making you a co-author.

Thanks!

**Comment by IrekFasikhov** [comment]
@leseb Hi,Sébastien! Sorry, did not see the message... I'm all for it. What you need from me? :))

**Comment by leseb** [comment]
Hi @IrekFasikhov, I just need your sign-off to add you as a co-author of a new library I'm writing :)

**Comment by IrekFasikhov** [comment]
Hi, @leseb 
"Signed-off-by: Irek Fasikhov <malmyzh@gmail.com>" :)

**Comment by leseb** [comment]
> Hi, @leseb
> "Signed-off-by: Irek Fasikhov [malmyzh@gmail.com](mailto:malmyzh@gmail.com)" :)

Thanks!

**Comment by leseb** [comment]
https://github.com/ceph/go-ceph/pull/496
